name: Build and Push Container Image to Artifact Registry
on:
  push:
    tags:
      - 'v*.*.*'
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE_FULL_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_ARTIFACT_REGISTRY_ID }}/todoapp-frontend

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      id: auth
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Authorize Atifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

    - name: Build Container Image
      run: docker build -t ${{ env.IMAGE_FULL_NAME }} .

    - name: Publisher Container Image
      run: docker push ${{ env.IMAGE_FULL_NAME }}
